### PR TITLE
Add readme entry for broadcast tuple hack

### PR DESCRIPTION
**Pull request by yuyichao**
Ref https://github.com/JuliaLang/Compat.jl/pull/326#issuecomment-279300787 @tkelman 

It's actually not that hard to make 0.4 support this too although a bit hard to make it as restricted as 0.5 and is probably not of great interest so I won't bother for now...

Hopefully skipping CI is fine, I don't think we check for white space anyway.....

[ci skip]

### CODE REVIEW

**Comment by TotalVerb** [comment]
I've run NEWS-update.jl on this branch.

**Comment by yuyichao** [comment]
I suppose the new commit doesn't need CI either?

**Comment by TotalVerb** [comment]
Sorry, my bad. I had CI skipped the NEWS-update.jl but not the merge commit (which I did through GitHub web UI).

I cancelled the Travis builds but I can't figure out how to cancel appveyor.

**Comment by yuyichao** [comment]
Jacob's AppVeyor doesn't look that busy so it's probably fine.

**Comment by yuyichao** [comment]
Will merge this and tag a new release very soon.

**Pull request merged**
