### PR TITLE
[3.x] add popat!

### PR DESCRIPTION
**Pull request by bkamins**
Later it will require backporting.

### CODE REVIEW

**Comment by martinholters** [comment]
It does not make much sense to put this on master, as the `popat!` has been added in Julia 1.5 and Compat master requires Julia 1.6 now. But I'm fine with directly adding it to the release-3 branch. Let me try to change the PR accordingly...

**Comment by martinholters** [comment]
Took the liberty to rebase the branch accordingly and fix the README a bit, please double-check.

**Comment by bkamins** [comment]
> It does not make much sense to put this on master, as the popat! has been added in Julia 1.5 and Compat master requires Julia 1.6 now.

Right - makes sense.

Thank you for rebasing - all looks good.

**Review by martinholters — APPROVED** [review]
LGTM

**Comment by bkamins** [comment]
@nalimilan - OK to merge and make a release?

**Comment by martinholters** [comment]
> @martinholters Can we just tag a 3.45.0?

Sure, that was the idea of bumping the version in this PR.

**Pull request merged**
