### PR TITLE
Add compatibility for rename from super() to supertype()

### PR DESCRIPTION
**Pull request by nalimilan**
Cf. https://github.com/JuliaLang/julia/pull/14338

### CODE REVIEW

**Comment by nalimilan** [comment]
The AppVeyor failures are unrelated.

**Comment by stevengj** [comment]
LGTM.  Looks like we need a separate PR to fix AppVeyor.

**Comment by tkelman** [comment]
we do, https://github.com/JuliaLang/Compat.jl/pull/156, but I was assuming `withenv` was already implemented here in my test, which it isn't.

**Comment by jiahao** [comment]
bump

**Comment by nalimilan** [comment]
I don't think anything more is needed here, right?

**Comment by jiahao** [comment]
Merging in the absence of any objections. (As noted above, AppVeyor failure is an unrelated issue on Windows.)

**Pull request merged**
