### PR TITLE
Compat for qr

### PR DESCRIPTION
**Pull request by martinholters**
This change applies the patch suggested in #160 and adds a test case.

### CODE REVIEW

**Comment by andreasnoack** [comment]
Thanks. It would be great if you could add definitions for `qrfact` and `qrfact!` as well.

**Comment by martinholters** [comment]
I would also add a few words to the README.md, I'm just not sure where. Is there a better place than the catch-all "Other changes" section? The fix is more similar to a renamed function, except that it's not a change of name but rather a change of type signature. Opinions?

**Comment by martinholters** [comment]
Ok, I have added an entry in the "Renamed functions" section of the README. Anything else this should see before a merge?

**Comment by andreasnoack** [comment]
@martinholters Sorry for the delay here.

**Pull request merged**
