### PR TITLE
Add `allequal`

### PR DESCRIPTION
**Pull request by mcabbott**
This adds https://github.com/JuliaLang/julia/pull/43354, which is in Julia 1.8

### CODE REVIEW

**Review by martinholters — APPROVED** [review]

**Comment by mcabbott** [comment]
Bump, can this be merged?

**Comment by mcabbott** [comment]
BTW, using this seems to cause https://github.com/JuliaDiff/ChainRules.jl/issues/598 . I've no idea why, though.

**Comment by martinholters** [comment]
I have no idea what's going on, but https://github.com/JuliaDiff/ChainRules.jl/issues/598#issuecomment-1063935985 says:

> This wasn't an issue with Compat either, but with an older version of JuliaFormatter in my startup.jl!

And I failed to reproduce the problem. If someone can come up with a reproducer, I'm willing to look at it, but I doubt it's Compat's fault.

**Comment by mcabbott** [comment]
Thanks for looking. I can't reproduce it either, but just wondered if you (or anyone) had ever seen something like this. I see nothing wrong with what either package is doing.

**Pull request merged**
