### PR TITLE
Add (sp)diagm pair constructors

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by fredrikekre** [comment]
I think we need something like:
```julia
# 0.7.0-DEV.2116
@static if VERSION < v"0.7.0-DEV.2116"
    Base.spdiagm(kv::Pair...) = spdiagm(last.(kv), first.(kv))
end

# 0.7.0-DEV.2161
@static if VERSION < v"0.7.0-DEV.2161"
    function Base.diagm(kv::Pair...)
        T = promote_type(map(x -> eltype(x.second), kv)...)
        n = mapreduce(x -> length(x.second) + abs(x.first), max, kv)
        A = zeros(T, n, n)
        for p in kv
            inds = diagind(A, p.first)
            for (i, val) in enumerate(p.second)
                A[inds[i]] += val
            end
        end
        return A
    end
end
```

**Comment by ararslan** [comment]
Ah, looks like the tests will need to be adjusted. I guess some sparse/dense equality stuff is 0.7 only?

**Comment by fredrikekre** [comment]
> Ah, looks like the tests will need to be adjusted. I guess some sparse/dense equality stuff is 0.7 only?

No, the difference is that `spdiagm` always return a square matrix on 0.7, which `diagm` has always done. I can fix up this PR later.

**Comment by ararslan** [comment]
Looks like the Travis failures are now that their macOS images are having issues. Thanks for your help here!

**Comment by fredrikekre** [comment]
failures are https://github.com/JuliaLang/julia/issues/24658

**Pull request merged**
