### PR TITLE
add @compat for .=

### LINKED ISSUE #285: .= assignment
0.5 introduced `x .= y` etcetera for in-place assignment.   It would be nice if `@compat` would translate this to `copy!(x, y)` in Julia 0.4.

Note that `x[...] .= y` should become `x[...] = y`.

Similarly for `.+=` and so on.

### PR DESCRIPTION
**Pull request by stevengj**
(closes #285)

### CODE REVIEW

**Comment by stevengj** [comment]
Test failure on nightly is unrelated to this PR.

**Comment by stevengj** [comment]
Restarting CI now that #293 is merged.

**Comment by ararslan** [comment]
Would it be worth amending the commit message to avoid pinging the [compat](https://github.com/compat) user? Perhaps `at-compat` or similar would work.

**Comment by stevengj** [comment]
Can rename the commit on merge

**Comment by ararslan** [comment]
Good idea. Looks good to me!

**Pull request merged**
