### PR TITLE
Set Project version to something > 0.69.0

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by stevengj** [comment]
Can we just bump to 1.0.0 (which probably should have been done long ago)?

**Comment by ararslan** [comment]
I'm also fine with that.

**Comment by ararslan** [comment]
So what should it be then, 1.0.0?

**Comment by martinholters** [comment]
Oops, sorry, just saw this (again) seconds after tagging 0.70.0. But yes, considering that we try quite hard not to do any breaking changes here, jumping to 1.0.0 would be appropriate, I'd say.

**Comment by martinholters** [comment]
I've tentatively bumped the version to 1.0.0 here. Should we go ahead and mere this and tag?

**Comment by martinholters** [comment]
Barring objections, I'll pull the trigger on this one tomorrow.

**Comment by ararslan** [comment]
No objection from me.

**Pull request merged**
