### PR TITLE
Add link for issue 21197

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by stevengj** [comment]
You know that you shouldn't be adding these links manually, right?.  You should run
```
julia /path/to/NEWS-update.jl README.jl
```
to re-generate the link list, where the `NEWS-update.jl` script can be found in the `doc` subdirectory of the Julia source code.

**Comment by musm** [comment]
Ah thanks!

**Comment by stevengj** [comment]
Would be a good idea to run the script and update this PR if there are any other missing links.

**Comment by musm** [comment]
There aren't any more missing links

**Comment by fredrikekre** [comment]
> There aren't any more missing links

```diff
diff --git a/README.md b/README.md
index 3e0f7fc..4b8c5c4 100644
--- a/README.md
+++ b/README.md
@@ -255,32 +255,8 @@ includes this fix. Find the minimum version from there.
 * Now specify the correct minimum version for Compat in your REQUIRE file by
 `Compat <version>`
 
-[#12819]: https://github.com/JuliaLang/julia/issues/12819
-[#13232]: https://github.com/JuliaLang/julia/issues/13232
-[#13338]: https://github.com/JuliaLang/julia/issues/13338
-[#13465]: https://github.com/JuliaLang/julia/issues/13465
 [#13681]: https://github.com/JuliaLang/julia/issues/13681
-[#13707]: https://github.com/JuliaLang/julia/issues/13707
-[#13744]: https://github.com/JuliaLang/julia/issues/13744
-[#14082]: https://github.com/JuliaLang/julia/issues/14082
-[#14338]: https://github.com/JuliaLang/julia/issues/14338
-[#14596]: https://github.com/JuliaLang/julia/issues/14596
-[#14601]: https://github.com/JuliaLang/julia/issues/14601
-[#14660]: https://github.com/JuliaLang/julia/issues/14660
-[#14766]: https://github.com/JuliaLang/julia/issues/14766
-[#14777]: https://github.com/JuliaLang/julia/issues/14777
-[#14805]: https://github.com/JuliaLang/julia/issues/14805
-[#15032]: https://github.com/JuliaLang/julia/issues/15032
-[#15192]: https://github.com/JuliaLang/julia/issues/15192
-[#15409]: https://github.com/JuliaLang/julia/issues/15409
-[#15708]: https://github.com/JuliaLang/julia/issues/15708
-[#15914]: https://github.com/JuliaLang/julia/issues/15914
-[#16154]: https://github.com/JuliaLang/julia/issues/16154
-[#16219]: https://github.com/JuliaLang/julia/issues/16219
-[#16563]: https://github.com/JuliaLang/julia/issues/16563
 [#16564]: https://github.com/JuliaLang/julia/issues/16564
-[#16603]: https://github.com/JuliaLang/julia/issues/16603
-[#16972]: https://github.com/JuliaLang/julia/issues/16972
 [#16986]: https://github.com/JuliaLang/julia/issues/16986
 [#17155]: https://github.com/JuliaLang/julia/issues/17155
 [#17302]: https://github.com/JuliaLang/julia/issues/17302
@@ -302,6 +278,7 @@ includes this fix. Find the minimum version from there.
 [#19784]: https://github.com/JuliaLang/julia/issues/19784
 [#19841]: https://github.com/JuliaLang/julia/issues/19841
 [#19950]: https://github.com/JuliaLang/julia/issues/19950
+[#20005]: https://github.com/JuliaLang/julia/issues/20005
 [#20022]: https://github.com/JuliaLang/julia/issues/20022
 [#20164]: https://github.com/JuliaLang/julia/issues/20164
 [#20203]: https://github.com/JuliaLang/julia/issues/20203
@@ -311,17 +288,17 @@ includes this fix. Find the minimum version from there.
 [#20418]: https://github.com/JuliaLang/julia/issues/20418
 [#20500]: https://github.com/JuliaLang/julia/issues/20500
 [#20974]: https://github.com/JuliaLang/julia/issues/20974
+[#21197]: https://github.com/JuliaLang/julia/issues/21197
 [#21257]: https://github.com/JuliaLang/julia/issues/21257
 [#21346]: https://github.com/JuliaLang/julia/issues/21346
-[#22005]: https://github.com/JuliaLang/julia/issues/22005
+[#21378]: https://github.com/JuliaLang/julia/issues/21378
 [#22064]: https://github.com/JuliaLang/julia/issues/22064
 [#22182]: https://github.com/JuliaLang/julia/issues/22182
 [#22350]: https://github.com/JuliaLang/julia/issues/22350
 [#22475]: https://github.com/JuliaLang/julia/issues/22475
-[#22633]: https://github.com/JuliaLang/julia/issues/22633
 [#22629]: https://github.com/JuliaLang/julia/issues/22629
-[#22666]: https://github.com/JuliaLang/julia/pull/22666
-[#22751]: https://github.com/JuliaLang/julia/pull/22751
-[#22761]: https://github.com/JuliaLang/julia/pull/22761
-[#22864]: https://github.com/JuliaLang/julia/pull/22864
-[#20005]: https://github.com/JuliaLang/julia/issues/20005
+[#22633]: https://github.com/JuliaLang/julia/issues/22633
+[#22666]: https://github.com/JuliaLang/julia/issues/22666
+[#22751]: https://github.com/JuliaLang/julia/issues/22751
+[#22761]: https://github.com/JuliaLang/julia/issues/22761
+[#22864]: https://github.com/JuliaLang/julia/issues/22864
```

**Comment by musm** [comment]
Looks correct the only one missing is the one in this PR . (Script looks like it deletes old references and also rearranges several ones)

**Comment by fredrikekre** [comment]
Yea, so why not do that? :)

> Would be a good idea to run the script and update this PR if there are any other missing links.

**Comment by musm** [comment]
@fredrikekre Do you mind submitting a PR for that then? Thanks

**Comment by fredrikekre** [comment]
#398

**Pull request closed without merging**
