### PR TITLE
Add support for multiarg InexactError, DomainError, OverflowError

### LINKED ISSUE #391: Add support DomainError constructors that ignore  inputs
@tkelman  comment in https://github.com/JuliaMath/SpecialFunctions.jl/pull/39#issuecomment-320432419

> May want to actually make use of the new DomainError feature? Maybe Compat could support 1 and 2-arg DomainError constructors that ignore the inputs. Hopefully that wouldn't have a performance cost on 0.6 and earlier.

### PR DESCRIPTION
**Pull request by timholy**
Fixes #391, CC @musm.

### CODE REVIEW

**Comment by timholy** [comment]
The error seems unrelated.

**Comment by tkelman** [comment]
Needs readme note

**Comment by timholy** [comment]
> Needs readme note

One might think I'd remember that without prompting by now. Thanks!

**Comment by musm** [comment]
Can we get a tag? There have been several commits since the last tag so it would be welcome

**Pull request merged**
