### PR TITLE
sort by version in readme

### PR DESCRIPTION
**Pull request by oxinabox**
AFAICT entries readme was ordered randomly?

Feel free to close if there is some pattern that I am missing

### CODE REVIEW

**Comment by martinholters** [comment]
Xref discussion in #666. You're right that the entries have no particular order. And not that I'm against sorting them, but is there any tangible benefit? Or is it just aesthetic?

**Comment by oxinabox** [comment]
It is a lot easier to navigate:
Find the last thing from the list of 5 things I need, scrolling up from the bottom.
I know that since it is sorted that means the other 4 must all also be covered by setting to this level

**Comment by martinholters** [comment]
Yes, that makes perfect sense! Although maybe reverse the order with newest on top? Scrolling down seems more intuitive (to me, at least).

**Comment by fredrikekre** [comment]
> Although maybe reverse the order with newest on top?

Was about to suggest this.

**Comment by martinholters** [comment]
Can you rebase to include the `Base.Order.ReverseOrdering` entry in the sorting? (Or we merge #678 first?)

**Comment by oxinabox** [comment]
I will rebase

**Comment by martinholters** [comment]
Superseded by #678.

**Pull request closed without merging**
