### PR TITLE
Add isnothing

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaLang/Compat.jl/issues/634

### CODE REVIEW

**Comment by musm** [comment]
0.6 failures look unrelated

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
@ararslan  does this look good to you? Is it ok to merge

**Comment by musm** [comment]
@fredrikekre thanks for the reminder, I finished adding news.

**Comment by musm** [comment]
merge?

**Comment by ararslan** [comment]
Looks like this is broken on 0.6, where `Nothing` is called `Void`. Since Compat defines a `Nothing`, this should be able to just live below that definition.

**Comment by musm** [comment]
good catch, I didn't see that.

**Comment by musm** [comment]
thanks, can you also tag a release

**Comment by ararslan** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/22427

**Pull request merged**
