### PR TITLE
New names for BigFloat precision and rounding functions

### PR DESCRIPTION
**Pull request by dpsanders**
Compatibility definitions for new function names for BigFloat precision and rounding functions from https://github.com/JuliaLang/julia/pull/13232

### CODE REVIEW

**Comment by stevengj** [comment]
Needs a README entry, too.

**Comment by dpsanders** [comment]
Thanks, added info to the README.

**Comment by dpsanders** [comment]
This is now ready.

**Comment by dpsanders** [comment]
Could you please tag a new version including this?

**Pull request merged**
