### PR TITLE
Add `Dates.canonicalize(::Period)`

### PR DESCRIPTION
**Pull request by nickrobinson251**
- Added to Dates stdlib in  https://github.com/JuliaLang/julia/pull/37391

### CODE REVIEW

**Comment by martinholters** [comment]
https://github.com/JuliaLang/julia/pull/37391 brings some more tests. Would it make sense to also include them here?

**Comment by nickrobinson251** [comment]
> [JuliaLang/julia#37391](https://github.com/JuliaLang/julia/pull/37391) brings some more tests. Would it make sense to also include them here?

🤷‍♂️ I can bring them across if you like? I didn't since one test is enough to test the dispatch this PR adds (and those other tests are testing that the `canonicalize` logic in Dates produces the expected results). Would you prefer i bring them across to match the linked PR?

**Comment by martinholters** [comment]
Yes, I think I'd prefer to bring them along. We can easily afford the extra run-time that costs and it would help catch any nasty surprises.

**Comment by nickrobinson251** [comment]
Cool :) i've brought over all the tests from the original PR and rebased to resolve conflicts

**Pull request merged**
