### PR TITLE
Add missing type aliases

### PR DESCRIPTION
**Pull request by yuyichao**
Needed for PyCall.jl

### CODE REVIEW

**Comment by yuyichao** [comment]
Adding README entry now.....

**Comment by yuyichao** [comment]
Test and README entry added.

**Comment by yuyichao** [comment]
Hold on. The version check is a little bit wrong and I think it's better to add all the missing ones together

**Comment by yuyichao** [comment]
Done. The only deprecated binding that is not in Compat is `UnionType` but that one is very different.

**Comment by simonster** [comment]
LGTM

**Comment by yuyichao** [comment]
Should we tag a new release after this? Or is there sth else that others want to be included (I guess we can always tag another one....).

**Comment by stevengj** [comment]
Tags are cheap...

**Pull request merged**
