### PR TITLE
RFC: Add new eltype definitions for v0.3 compatibility

### PR DESCRIPTION
**Pull request by kmsquire**

### CODE REVIEW

**Comment by kmsquire** [comment]
Currently with ambiguity, overwritten definition warnings on v0.3:

```julia
julia> import Compat
Warning: New definition
    eltype(Type{T<:Top},) at /Users/kevin/.julia/v0.3/Compat/src/Compat.jl:159
is ambiguous with:
    eltype((T...,),) at tuple.jl:25.
To fix, define
    eltype((_<:Type{T<:Top}...,),)
before the new definition.
Warning: Method definition eltype(Any,) in module Base at abstractarray.jl:10 overwritten in module Compat at /Users/kevin/.julia/v0.3/Compat/src/Compat.jl:162.
```

**Comment by kmsquire** [comment]
Okay, now left with

```julia
Warning: Method definition eltype(Any,) in module Base at abstractarray.jl:10 overwritten in module Compat at /Users/kevin/.julia/v0.3/Compat/src/Compat.jl:163.
```

(before 0.4.0-dev+3253).  

Probably not any way around this, unless https://github.com/JuliaLang/julia/pull/9284 is backported.  (And even then, earlier versions of v0.3 will show the warning.)  Thoughts.

Cc: @JeffBezanson

**Comment by kmsquire** [comment]
Needed by https://github.com/JuliaLang/Iterators.jl/pull/38.

**Comment by timholy** [comment]
This looks fine to me. I agree the "overwritten" warning is unfortunate, but I don't see any way around it. If you're still interested in merging this, I'd go for it.

**Comment by simonster** [comment]
I'm not sure I like the idea of every package that uses Compat printing a warning on load. But I think defining `eltype{T}(x::T)` instead of `eltype(x)` might work around that.

**Comment by hayd** [comment]
This needs a rebase! :)

**Comment by TotalVerb** [comment]
Since METADATA will be frozen for v0.3 soon, I suppose some of these issues can be closed? https://github.com/JuliaLang/METADATA.jl/pull/6146

**Pull request closed without merging**
