### PR TITLE
WIP: Backwards compatibility for Cartesian macros (ngenerate & nsplat)

### PR DESCRIPTION
**Pull request by timholy**
Just queuing this up, but the changes to master have to happen first.

### CODE REVIEW

**Comment by simonster** [comment]
This doesn't seem to work for functions that use both `@ngenerate` and Cartesian macros, e.g.:

```
julia> @ngenerate N Nothing function f(X::NTuple{N,Any}...)
       @ncall N println X
       end;

julia> f((1, 2))
ERROR: UndefVarError: X_1 not defined
 in anonymous at none:2
```

**Comment by simonster** [comment]
I thought maybe just calling `macroexpand` from inside the stagedfunction might work, but that gives me an undefined symbol error. It seems like the macro expansion takes place in whatever module is being interpreted and not the module that calls `macroexpand`.

**Comment by simonster** [comment]
#42 seems to fix this.

**Comment by timholy** [comment]
Thanks, @simonster.

**Pull request merged**
