### PR TITLE
Add Matrix(I, dims) constructor

### LINKED ISSUE #468: Add `Matrix(I, n, m)` method
In Julia v0.7 you don't need to specify the eltype of the matrix - it is inferred from the `UniformScaling{T}` input. Compat has only defined the `Matrix{T}(::UniformScaling, n, m)` method.

```
# Julia v0.6.2
julia> using Compat

julia> Matrix(I, 4, 4)
ERROR: MethodError: no method matching Array{T,2} where T(::UniformScaling{Int64}, ::Int64, ::Int64)
Closest candidates are:
  Array{T,2} where T(::Compat.Uninitialized, ::Any...) at string:5
  Array{T,2} where T(::Integer, ::Integer) at sysimg.jl:105

julia> Matrix{Float64}(I, 4, 4)
4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
```

### PR DESCRIPTION
**Pull request by ararslan**
fix  #468

### CODE REVIEW

**Comment by fredrikekre** [comment]
Note that these where intentionally excluded in https://github.com/JuliaLang/Compat.jl/pull/412

**Comment by ararslan** [comment]
Why the revival? Don't the concerns in #412 still apply?

**Comment by fredrikekre** [comment]
> Why the revival? Don't the concerns in #412 still apply?

Meh, it is not the fault of the `Matrix `constructor that the element type of `I` has changed, that is documented as a breaking change separately :)

**Comment by ararslan** [comment]
Works for me :)

**Comment by martinholters** [comment]
Just so it be said: I didn't include them in #412 because I was unsure about them, not because I was opposed to them.

**Pull request merged**
