### PR TITLE
Add argmin and argmax

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by martinholters** [comment]
Too bad I'm a bit late, but I think this is not quite correct because for ndims>1, `indmin` returns a linear index in Julia 0.6 (more specifically before 0.7.0-DEV.1660), while `argmin` returns a `CartesianIndex`. So we should define `argmin` as a wrapper around `indmin`, putting the result into a `CartesianIndex`, if `VERSION < v"0.7.0-DEV.1660"`.

**Comment by fredrikekre** [comment]
Good catch, lets make sure we fix that before making a new Compat release.

**Comment by ararslan** [comment]
Yes very good catch, @martinholters. Would you be willing to submit a PR for that?

**Comment by martinholters** [comment]
Yes, but might need a day or two.

**Comment by ararslan** [comment]
Sure thing. I'll see if I can get around to it sooner and I'll ping you if I beat you to it, but I might not be able to.

**Pull request merged**
