### PR TITLE
Backport 3.x: `stack` (Julia PR 43334)

### LINKED ISSUE #778: Backport stack to 3.x branch
@ararslan - #777 also needs to be backported to 3.46 branch, as 4.x branches support only Julia 1.6 and newer.

### PR DESCRIPTION
**Pull request by ararslan**
Backport of #777 to the `release-3` branch.

Closes #778

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you (although there seem to be some backporting issues) CC @mcabbott

**Comment by ararslan** [comment]
Working on that now. The one I'm looking into currently is the lack of `Iterators.peel` but I think I have an idea...

**Comment by mcabbott** [comment]
Never tried this with ancient Julia, but notice the same error on 1.7 "LoadError: cannot assign a value to variable Base.IteratorSize from module Compat" which is weird. 

My first guess was that it relied on ` @constprop` but the Compat version of that does seem to have been backported to this branch.

**Comment by ararslan** [comment]
I fixed the `IteratorSize` one locally, that was an `include` order issue.

**Comment by ararslan** [comment]
Alright, the one remaining failure now is on Julia 1.0, something is causing a `MethodError` where the test expects an `ArgumentError`. My computer won't run my Julia 1.0 binaries anymore so I'm not able to diagnose.

**Comment by mcabbott** [comment]
On 1.0 with this PR I get this error:
```
julia> stack([(1,2), (3,4,5)]; dims=1)
ERROR: MethodError: no method matching UnitRange(::Int64)
Closest candidates are:
  UnitRange(::T<:Real, ::T<:Real) where T<:Real at range.jl:257
  UnitRange(::AbstractUnitRange) at range.jl:857
Stacktrace:
 [1] iterate at ./generator.jl:47 [inlined]
 [2] _collect(::Base.OneTo{Int64}, ::Base.Generator{Base.OneTo{Int64},Type{UnitRange}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:632
 [3] collect_similar at ./array.jl:561 [inlined]
 [4] map at ./abstractarray.jl:1987 [inlined]
 [5] _stack_size_check at /Users/me/.julia/packages/Compat/Qd33g/src/Compat.jl:1613 [inlined]
 [6] _dim_stack!(::Val{1}, ::Array{Int64,2}, ::Tuple{Int64,Int64}, ::Base.Iterators.Rest{Array{Tuple{Int64,Int64,Vararg{Int64,N} where N},1},Int64}) at /Users/me/.julia/packages/Compat/Qd33g/src/Compat.jl:1604
```

**Comment by ararslan** [comment]
😳

**Comment by ararslan** [comment]
Incredible, I fixed it on 1.0 and broke it everywhere else

**Comment by mcabbott** [comment]
That looks right. I guess the inference tests don't like non-const `_tuple_axes = axes`.

**Comment by ararslan** [comment]
Finally!

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
