### PR TITLE
Add using Dates compatibility

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by tkelman** [comment]
What's the intended usage here? Putting `using Dates` inside the macro's transformation function doesn't do much good.

**Comment by quinnj** [comment]
If I have a package that depends on `Dates`, on 0.3, I just need to do `using Dates` and have `Dates` in the REQUIRES file. For 0.4, I need to do `using Base.Dates`. It hurts my head to think about right now, so I'm going to try and think about the best way to do this a little later.

**Comment by tkelman** [comment]
I'm not sure whether `using` statements can be metaprogrammed via `@compat using Foo`, but for consistency with the rest of the way Compat works it would probably have to translate the 0.4 syntax, `@compat using Base.Dates`, to `using Dates` on 0.3. If that can work.

**Comment by jakebolewski** [comment]
You could so the symbolic argument rewrite, and splice the new expression into a top level node. 

```julia
Expr(:toplevel, $(rewritten using Expr))
```

**Comment by hayd** [comment]
This would be good for Markdown also. You have to put Dates in the REQUIRE (which is kindof annoying).

**Pull request closed without merging**
