### PR TITLE
Add `walkdir` from Base.

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Based directly on https://github.com/JuliaLang/julia/pull/13707. Any opposition to adding this?

Tests pass locally on `0.3.13-pre+5`, `0.4.6-pre+4`, and `0.5.0-dev+3258`.

### CODE REVIEW

**Comment by tkelman** [comment]
needs an end of file rebase. no objection here

**Comment by MichaelHatherly** [comment]
Rebased. Should we hold off on the latest tag, https://github.com/JuliaLang/METADATA.jl/pull/4884, until this is merged?

**Comment by tkelman** [comment]
Not surr what you mean hold off, it was already tagged but not merged yet. More work to change that than just do another tag after merging this.

**Comment by MichaelHatherly** [comment]
> More work to change that than just do another tag after merging this.

Yes, not sure why I thought that would be simpler than just doing another tag afterwards.

**Pull request merged**
