### PR TITLE
bin/version.sh: check code for generating version numbers into bin

### PR DESCRIPTION
**Pull request by StefanKarpinski**
This could probably use a better name.

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
Leaving this here for discussion of whether putting this in a file is a good idea and/or if we should make the script fancier and/or rewrite it in Julia. It seems like almost everyone who wants to add anything to this package will want this script saved somewhere.

**Comment by tkelman** [comment]
You spelled the file name wrong

I'll need to dig up where I wrote out an explanation of why, but I think we should add a note here that you want to run this script on the **merge commit** where a change gets added to master. Otherwise the build-number counting can be off.

**Comment by StefanKarpinski** [comment]
Jeez. Thanks for catching that, @tkelman.

**Comment by StefanKarpinski** [comment]
Fixed the file naming issue.

**Comment by stevengj** [comment]
I would add an `echo -n "0.4.0-dev+"` to the script so that it outputs the whole version string.

**Comment by StefanKarpinski** [comment]
See also: https://github.com/JuliaLang/julia/blob/f2bd73132765cf850ffe83996e8d6c5473dfda8f/contrib/commit-name.sh

**Pull request merged**
