### PR TITLE
Revert function first finalizers due to ambiguities

### PR DESCRIPTION
**Pull request by ararslan**
cc also @KristofferC

### CODE REVIEW

**Comment by iamed2** [comment]
How about a `@compat` recipe that flips the call to `finalizer` on old versions?

**Comment by ararslan** [comment]
I don't know that I'll have time to look into that myself but if someone wants to take that on, it seems like a reasonable idea.

**Comment by rofinn** [comment]
I'll give it a shot. I'm pretty sure we'll want it for Memento and Dispatcher at least.

**Comment by fredrikekre** [comment]
> I'll give it a shot. I'm pretty sure we'll want it for Memento and Dispatcher at least.

Ah, sorry, I already had the fix, should have mentioned it

**Pull request merged**
