### PR TITLE
Add definitions for mmap

### PR DESCRIPTION
**Pull request by rened**
@timholy

### CODE REVIEW

**Comment by timholy** [comment]
Wow, thanks! CC @quinnj.

**Comment by tkelman** [comment]
Speaking of @quinnj, do you have an AppVeyor account? I've already got too many packages under my account, would you be willing to turn on AppVeyor here under yours?

**Comment by quinnj** [comment]
Hey @tkelman, happy to help however I can. What do I need to do exactly?

**Comment by tkelman** [comment]
Go to appveyor.com, either register for a new account or sign in via github auth, then find "add projects" and click the plus sign for JuliaLang/Compat.jl. I can check the webhooks here to see if that goes through correctly, and if it does I'll open a PR adding the appveyor.yml file.

**Comment by quinnj** [comment]
Ok, done. (I think)

**Comment by quinnj** [comment]
Also, thanks @rened for this. Definitely great to have.

**Comment by tkelman** [comment]
Hm, I don't think that added the webhook. Can you go to AppVeyor settings for this project, find and paste the Webhook URL here?

**Comment by quinnj** [comment]
https://ci.appveyor.com/api/github/webhook?id=oq7mht690oe9pj62

**Comment by tkelman** [comment]
Great, see https://github.com/JuliaLang/Compat.jl/pull/124 - I'll add the readme badge too while I'm at it. I should actually make a proper tutorial with these steps and put it somewhere. If you need to add or adjust the webhook manually, see https://github.com/JuliaOpt/JuMP.jl/pull/362#issuecomment-70610293

**Pull request merged**
