### PR TITLE
add KeySet

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
ref https://github.com/JuliaCollections/DataStructures.jl/pull/348

**Comment by fredrikekre** [comment]
This is a bit iffy. Probably better for packages that need this to solve it locally. I guess this type is not used that much anyway.

**Comment by andyferris** [comment]
> Probably better for packages that need this to solve it locally. I guess this type is not used that much anyway.

I find this hard to judge (I've had little experience with `Compat` anyway).

**Comment by fredrikekre** [comment]
In all registered packages, apart from in DataStructures, this: https://github.com/BenLauwens/ResumableFunctions.jl/blob/ec55bcf9bc1cd24ba84b28743e10953795f1d90d/src/transforms.jl#L22 is the only place where `KeyIterator` is used. Since this PR does not offer the complete functionality of `KeySet` I think it is better to do local fixes for this, and not provide it from `Compat`.

**Pull request closed without merging**
