### PR TITLE
Add parentmodule

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like this will need #463 in order to pass tests on Travis. (The Windows nightly is apparently pretty old.)

**Comment by ararslan** [comment]
Hmm, 0.7 is failing here saying that `Diagonal` moved to LinearAlgebra. Which is weird given that there's a `using Compat.LinearAlgebra` at the top...

**Comment by fredrikekre** [comment]
Doesn't happen on master, but I get that failure locally when checking out this PR, but after rebasing on master everything works.

**Comment by ararslan** [comment]
Cool, thanks for investigating!

**Pull request merged**
