### PR TITLE
Drop v0.3 support

### LINKED ISSUE #31: at-compat macro does not work with semi-colon in "split"
Note the `;` in the second expression

```julia
macroexpand(:(@compat split("a?b?c?","?", limit=2, keep=false)))
:(split("a?b?c?","?",2,false))

macroexpand(:(@compat split("a?b?c?","?"; limit=2, keep=false)))
:(split("a?b?c?","?"; limit=2,keep=false))
```

### LINKED ISSUE #46: Add support for redesign of Triangular
As mentioned in https://github.com/JuliaLang/julia/pull/9779, it would be nice if the redesign of Triangular would get support in Compat.jl

### LINKED ISSUE #61: Pair() for 0.3?
Is `Pair` a good candidate for inclusion into `Compat`, or is this a request better made to the 0.3 maintainers (to cherrypick it)?

### LINKED ISSUE #77: size with multiple dim arguments
On Julia 0.4 I can do this:

```julia
a = rand(10, 10, 3)
size(a, 1, 3) == (10, 3)
```

However with 0.3.7 and `using Compat` I get a `MethodError`.

Is this something that Compat should support?

### LINKED ISSUE #87: rem() for integer types
Compat.jl is missing support for 0.4-style integer truncations, e.g. `123 % Uint8`.

### LINKED ISSUE #89: Cint not working in 0.3.7
```
julia> Pkg.checkout("Compat")
INFO: Checking out Compat master...
INFO: Pulling Compat latest master...
INFO: Upgrading Calculus: v0.1.6 => v0.1.8

julia> using Compat

julia> @compat(Cint(false))
ERROR: type cannot be constructed

julia> versioninfo()
Julia Version 0.3.7
Commit cb9bcae (2015-03-23 21:36 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.status()
2 required packages:
 - GLPlot                        0.0.5+             master
 - Jewel                         1.0.4
37 additional packages:
 - BinDeps                       0.3.12
 - Calculus                      0.1.8
 - Color                         0.4.5
 - Compat                        0.4.4              master
 - Compose                       0.3.12
 - DataStructures                0.3.9
 - Datetime                      0.1.7
 - Docile                        0.5.2
 - DualNumbers                   0.1.3
 - FactCheck                     0.2.7
 - FixedPointNumbers             0.0.7
 - GLAbstraction                 0.0.5+             master
 - GLFW                          1.0.0-alpha.6
 - GLText                        0.0.4
 - GLWindow                      0.0.5+             master
 - Graphics                      0.1.0
 - Homebrew                      0.1.14
 - Images                        0.4.36
 - ImmutableArrays               0.0.7
 - Iterators                     0.1.8
 - JSON                          0.4.3
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.8.4
 - Lumberjack                    0.0.3
 - ModernGL                      0.0.5+             master
 - Mustache                      0.0.9
 - NaNMath                       0.0.2
 - Quaternions                   0.0.4
 - Reactive                      0.2.0
 - Requires                      0.1.2
 - SHA                           0.0.4
 - SIUnits                       0.0.3
 - TexExtensions                 0.0.2
 - URIParser                     0.0.5
 - UUID                          0.0.2
 - Zlib                          0.1.8
```

### LINKED ISSUE #94: Nullable with subtype
I am having a problem when I assign a value to a Nullable which it a sub-type of the type contained by the Nullable.  This works in 0.4, but not with Compat.

Here is the problem:

```
julia> abstract Parent

julia> immutable Child <: Parent end

julia> type Container x::Nullable{Parent} end

julia> c = Container(Child())
ERROR: `convert` has no method matching convert(::Type{Nullable{Parent}}, ::Child)
 in Container at no file
```

However, I have no idea how you solve this because:

```
julia> convert{T,S<:T}(::Type{Nullable{T}}, s::S) = Nullable{T}(s)
ERROR: T not defined
```

### LINKED ISSUE #102: `@compat` for `[]`?
In julia `0.4`, the `{}` syntax is deprecated:

```
julia> {}

WARNING: deprecated syntax "{}".
Use "[]" instead.
0-element Array{Any,1}
```

Changing `{}` to `[]` leads to the correct behavior on julia `0.4`.  However, on julia `0.3` it results in a different type, `Array{None,1}`:

```
julia> []
0-element Array{None,1}
```

I think one of two things should be done:

1. Make `@compat []` transform to `Any[]` on julia `0.3`; or,
2. Make the deprecation notice suggest using `Any[]` instead of `[]` in place of `{}`.

(If the second option makes more sense, this bug should really be filed against julia instead.)

Also, apologies if this has been discussed elsewhere; it's a fairly difficult issue to search for.

### LINKED ISSUE #112: lufact pivot argument
`lufact` since https://github.com/JuliaLang/julia/commit/f9da849d7548db055e686cbbebc43b042b5b87f7 has been type-stable, much like `chol` which has already been handled. Could an entry to `Compat.jl` be added for `lufact` too? I need this for `CUSPARSE.jl` tests.

### LINKED ISSUE #277: Dropping v0.3 support
Should support for v0.4 development versions be dropped as well as raising the minimum version in REQUIRE?

### PR DESCRIPTION
**Pull request by TotalVerb**
I have intentionally avoided touching the tests in this PR, so that it is more certain that nothing has regressed. Tests that are testing functionality in `Base` can be removed in a later PR.

Closes #277 by addressing it directly.

Also closes the following issues on account of the issues becoming obsolete, as they request a feature or bugfix in Base as of v0.4.0 release:

- closes #31
- closes #46
- closes #61 
- closes #77 
- closes #87 
- closes #89 
- closes #94 
- closes #102 
- closes #112 

Also closes the following PRs on account of the added functionality being present in Base as of the v0.4.0 release:

- closes #43 
- closes #78 
- closes #91 
- closes #92 
- closes #120

### CODE REVIEW

**Comment by tkelman** [comment]
I don't see why it's useful to delete all the code.

**Comment by andreasnoack** [comment]
Less code to keep track of and lower risk of clashes between old and new definitions. Why would like to keep it if we drop support for 0.3?

**Comment by stevengj** [comment]
I think the argument is that it is will be harder and harder to maintain 0.3 compatibility going forward as we add new 0.6 features.  And once we drop 0.3 support for new features, we might as well delete the corresponding code for old features (since 0.3 users can still use the older Compat versions).

**Comment by tkelman** [comment]
I disagree that deleting the code is worthwhile. It may be necessary to backport something to an 0.3-supporting branch, in which case it's better to have the code diverge less.

**Comment by TotalVerb** [comment]
The code deletion is not urgent and can be discussed at a later time. I'll rebase it out of this PR.

**Comment by TotalVerb** [comment]
All the code deletions have been reverted now.

**Pull request merged**
