### PR TITLE
srand is now Random.seed!

### PR DESCRIPTION
**Pull request by rdeits**
https://github.com/JuliaLang/julia/pull/28295

### CODE REVIEW

**Comment by rdeits** [comment]
Ah, this doesn't work because the `Compat.Random` module only ends up containing the *exported* symbols from `Base.Random`. I can either: 

1. Import every symbol from `Base.Random` into `Compat.Random` individually
2. Instead of creating a separate `Compat.Random` module, just do `@eval Random const seed! = srand` 

Any opinions?

**Comment by stevengj** [comment]
Let's just manually import symbols that are documented but not exported.

**Comment by rdeits** [comment]
Ok, this is a bit closer now. The only things I know I'm missing are the new `randperm!` and `randcycle!` functions.

**Comment by rdeits** [comment]
Bump?

**Comment by AsafManela** [comment]
bump

**Comment by traktofon** [comment]
Bump? Or is it considered obsolete by now?

**Comment by martinholters** [comment]
This broke (at least) `StatsBase` because it doens't provide `RangeGenerator` and `GLOBAL_RNG` in `Random`. Fix incoming.

**Pull request merged**
