### PR TITLE
add devnull, stdin, stdout and stderr

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Hmm... This will not work becuse of functions changing `Base.stdout` but `Compat.stdout` will always point to the old one.

**Comment by stevengj** [comment]
Yes, it needs to be done with `@compat` to rewrite at the source level, I think.

**Comment by yuyichao** [comment]
Not necessarily.

```julia
julia> module A
       a = 1
       end
Main.A

julia> module B
       import ..A.a
       end
Main.B

julia> B.a
1

julia> A.a
1

julia> A.eval(:(a = 2))
2

julia> B.a
2

julia> A.a
2
```

**Comment by yuyichao** [comment]
Actually nvm, I guess this doesn't work for renaming...

**Pull request closed without merging**
