### PR TITLE
Add Compat for standard library imports

### PR DESCRIPTION
**Pull request by TotalVerb**
Alternative to #403. Feedback on which approach is preferable would be helpful.

cc @yuyichao

### CODE REVIEW

**Comment by nalimilan** [comment]
I don't have strong feelings about which solution is best, except that I'd rather use the one which FemtoCleaner will be able to remove automatically after dropping support for 0.6 (if it exists).

**Comment by TotalVerb** [comment]
I think both are able to be removed easily by FemtoCleaner.

**Comment by musm** [comment]
Maybe just stick to current convention  as in this PR. We already have to do e.g. `using Compat.Sys.islinux` so this seems consistent.

**Comment by TotalVerb** [comment]
It is not quite the same because `Compat.Sys` need not be deprecated and removed, whereas `Compat.Test` will be...

**Comment by yuyichao** [comment]
There are many that needs deprecation and removed.

**Comment by TotalVerb** [comment]
Which existing things need deprecation?

**Comment by yuyichao** [comment]
Currently active one that needs deprecation includes `MathConstants`, `invokelatest`, `StringVector`.

Also see the currently deprecating list which includes `KERNEL`, `UTF8String`, `ASCIIString`, `unsafe_convert`, `remote_do`, `Filesystem`, `AsyncCondition`, `promote_eltype_op`, `@irrational`, `@blasfunc`.

**Comment by TotalVerb** [comment]
I'm not convinced that this is a module rename and should be handled similarly. `using Test` does something very different than `using Compat.Test` does, because it's loading a package, whereas `using Compat.Test` is just importing the exported symbols of an already-loaded module. Isn't it possible that standard library packages will not be loaded by default in the future?

**Comment by TotalVerb** [comment]
In the spirit that "something is better than nothing", I am merging this PR. It will require a deprecation cycle later, but femtocleaner is perfectly capable of cleaning such things up.

**Pull request merged**
