### PR TITLE
Implement lower case conversion methods

### PR DESCRIPTION
**Pull request by jakebolewski**
Closes https://github.com/JuliaLang/Compat.jl/issues/49

cc @jiahao

### CODE REVIEW

**Comment by timholy** [comment]
Yay, thanks so much!

**Comment by jiahao** [comment]
woot

**Comment by aviks** [comment]
Yay!! Just saw a ton of deprecation messages in one my project, and came looking for this. Thanks!

**Comment by mbauman** [comment]
Shouldn't these be getting lowered to `convert(T, ...)` instead of their lowercase equivalents? I think that would be a bit more consistent between the two versions.

**Comment by jakebolewski** [comment]
Yes, I needed something working last night but this way enabled the `map(::Int, x)` -> `int(x)` change.  Should be fixed now.

**Comment by mbauman** [comment]
Awesome.  Thank you!

**Pull request merged**
