### PR TITLE
Compat for SparseArrays module

### PR DESCRIPTION
**Pull request by yuyichao**
Ref JuliaLang/julia#13440

Looks like the document needs some update for JuliaLang/julia#13440 too.

@mbauman

### CODE REVIEW

**Comment by mbauman** [comment]
LGTM.  Thanks.

I'm not surprised I missed some documentation.  Could you point me to the spots that still need updating?

**Comment by yuyichao** [comment]
I just did a search of SparseMatrix and saw some matches. I suppose most of them needs update.

**Comment by yuyichao** [comment]
Actually none of them are actually in the sparse matrix doc but should still be updated.

**Comment by yuyichao** [comment]
Just realized that I should probably add doc for this ....

**Pull request merged**
