### PR TITLE
Deprecation of `$` in favour of `xor`

### PR DESCRIPTION
**Pull request by simonbyrne**
https://github.com/JuliaLang/julia/pull/18977

### CODE REVIEW

**Comment by nalimilan** [comment]
Could you add a test?

**Comment by GunnarFarneback** [comment]
This doesn't cover `⊻=`. Is it at all possible to support that with Compat?
```
julia> using Compat

julia> x = true
true

julia> x $= true
false

julia> x ⊻= true
ERROR: syntax: unexpected "="
```

**Comment by stevengj** [comment]
No, `⊻=` isn't parsed as an operator.  You have to write `x = x ⊻ true`

**Comment by GunnarFarneback** [comment]
Ok. That's a bit unfortunate for the specific piece of code I'm working with since `⊻=` will look nicer once 0.5 support can be dropped.

In case someone else should run into this, this is the alternative solution I chose for the 0.5 to 0.6 transition (skipping Compat):
```
if isdefined(:xor)
    macro x(ex)
        arg1 = ex.args[1]
        arg2 = ex.args[2]
        return esc(:($(arg1) = $(arg1) ⊻ $(arg2)))
    end
else
    const ⊻ = $
    macro x(ex)
        return esc(ex)
    end
end
```
and decorating all use of `$=` with the `@x` macro.

**Pull request merged**
