### PR TITLE
Add support for set_zero_subnormals()

### PR DESCRIPTION
**Pull request by davidavdav**
As requested in [this thread](https://groups.google.com/d/msg/julia-dev/XiZoKWed7B8/EVOjrGulwMgJ).

### CODE REVIEW

**Comment by stevengj** [comment]
Needs a rebase. 

Also, it seems like you should also provide get_zero_subnormals too.

**Comment by yuyichao** [comment]
> Also, it seems like you should also provide `get_zero_subnormals` too.

I don't think the c runtime for 0.3 provides that.

**Comment by davidavdav** [comment]
Yes, that was my assessment at the time, so I didn't include that.

**Comment by stevengj** [comment]
Ah, okay.  Just a rebase, then, and this should be good to merge I think?

**Pull request closed without merging**
