### PR TITLE
Use new call overload syntax

### PR DESCRIPTION
**Pull request by andreasnoack**
This change eliminates parser warnings.

~~Update: I'll update the commit message when #213 has been merged because I'll probably have to fix some conflicts anyway.~~

### CODE REVIEW

**Comment by andreasnoack** [comment]
@tkelman I'm not sure what the AV errors are here but could you try restarting AV when #213 has been merged?

**Comment by tkelman** [comment]
the failure is actually https://github.com/JuliaLang/Compat.jl/pull/217 - appveyor ran on newer nightlies than travis did

**Comment by tkelman** [comment]
I was going to wait until #213 was merged as you suggested, but alright to queue it

**Comment by andreasnoack** [comment]
Oh. I confused my two PRs. I'll also have to update the commit message here. Will do that now.

**Pull request merged**
