### PR TITLE
Define X_n variables on entry to function generated by nsplat/ngenerate

### PR DESCRIPTION
**Pull request by simonster**
This appears to fix DataArrays. cc @timholy

### CODE REVIEW

**Comment by timholy** [comment]
LGTM. As you surely know, you can also use the `@nexprs N (d->X_d = ...)` construct, but given that you have to splice in the symbol your version is probably easier. Merge at will. (And then we should tag a new release.)

**Comment by simonster** [comment]
Hmm, it seems like `@nexprs` might be a better idea if `X` is a heterogeneously typed tuple, since it looks like `X_1, X_2 = X` doesn't give us proper type information.

**Comment by timholy** [comment]
Nice. I hadn't remembered that distinction, but it makes sense.

**Comment by simonster** [comment]
Thanks for reviewing!

**Pull request merged**
