### PR TITLE
backport findprev, findlast & tests

### PR DESCRIPTION
**Pull request by StefanKarpinski**
See https://github.com/JuliaLang/julia/commit/e3aa57efbc6542efbcc7feac9b1309d628ac6f12

### CODE REVIEW

**Comment by tkelman** [comment]
Very confusing to tag this as 0.3.8, when 0.4.1 is already tagged in metadata...

**Comment by StefanKarpinski** [comment]
Sorry, I seem to have been having a very off day when I did this.

**Comment by StefanKarpinski** [comment]
What's the best fix? Retag the same version as 0.4.2?

**Comment by tkelman** [comment]
Sure. Worth mentioning this addition in https://github.com/JuliaLang/Compat.jl/blob/master/README.md#new-functions too.

And determining how to make Pkg more robust against out-of-order tagging.

**Pull request merged**
